import styled from "@emotion/styled";
import Head from "next/head";
import Image from "next/image";
import CategoriesCard from "../src/components/CategoriesCard";
import HomeBanner from "../src/components/HomeBanner";
import Layout from "../src/layout";

const MainContainer = styled.main`
  display: flex;
  justify-content: center;

  .flex {
    display: flex;
    flex-direction: column;
  }

  .container-title {
    font-weight: 600;
    font-size: 18px;
    margin-bottom: 12px;
    color: rgba(0, 0, 0, 0.85);
  }

  .categories-container {
    .categories {
      display: flex;
      flex-wrap: wrap;
    }
  }
`;

export default function Home({ categoryData }) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <div className="set-width">
          <HomeBanner />

          <div className="categories-container flex">
            <span className="container-title">Explore Categories</span>
            <div className="categories">
              {categoryData.map((data, index) => (
                <CategoriesCard name={data.name} link={data.id} key={index} />
              ))}
            </div>
          </div>

          {/* <div className="books-container flex">
            <span className="container-title">Latest Release</span>
            <div className="books"></div>
          </div> */}
        </div>
      </MainContainer>
    </Layout>
  );
}

export async function getServerSideProps(context) {
  const categoryRes = await fetch(
    `https://asia-southeast2-sejutacita-app.cloudfunctions.net/fee-assessment-categories`
  );
  const categoryData = await categoryRes.json();

  return {
    props: {
      categoryData: categoryData,
    }, // will be passed to the page component as props
  };
}
